"""add title and make candidate_id nullable on scheduled_lessons

Revision ID: 05c249affe31
Revises: 5c1aac1d237c
Create Date: 2026-03-14 20:23:36.672203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c249affe31'
down_revision = '5c1aac1d237c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.alter_column('candidate_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_lessons', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('title')

    # ### end Alembic commands ###
