"""create all tables

Revision ID: 3559cc0f8f90
Revises: 
Create Date: 2026-03-10 00:10:36.278908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3559cc0f8f90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('nui', sa.String(length=50), nullable=True),
    sa.Column('tvsh', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('representative', sa.String(length=200), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('verification_text', sa.Text(), nullable=True),
    sa.Column('verification_code', sa.String(length=50), nullable=True),
    sa.Column('theory_hours', sa.Integer(), nullable=True),
    sa.Column('practical_hours', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contract_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_licensed', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_categories_tenant_code')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('expense_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_expense_type_tenant_name')
    )
    with op.batch_alter_table('expense_types', schema=None) as batch_op:
        batch_op.create_index('idx_expense_types_tenant', ['tenant_id'], unique=False)

    op.create_table('municipalities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('municipalities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_municipalities_country_id'), ['country_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('personal_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activation_count', sa.Integer(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_users_tenant_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_audit_logs_tenant_date', ['tenant_id', 'created_at'], unique=False)
        batch_op.create_index('idx_audit_logs_user', ['user_id', 'created_at'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('participant_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('idx_conversations_tenant', ['tenant_id', 'last_message_at'], unique=False)

    op.create_table('instructors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('personal_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('hours_realized', sa.Integer(), nullable=True),
    sa.Column('license_info', sa.String(length=200), nullable=True),
    sa.Column('cost_per_candidate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_instructors_tenant_code')
    )
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instructors_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instructors_user_id'), ['user_id'], unique=True)

    op.create_table('places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('municipality_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_places_municipality_id'), ['municipality_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_conversation', ['tenant_id', 'conversation_id', 'created_at'], unique=False)
        batch_op.create_index('idx_messages_recipient', ['tenant_id', 'recipient_id', 'is_read'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('chassis_number', sa.String(length=50), nullable=True),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('registration_expiry', sa.Date(), nullable=True),
    sa.Column('technical_control_date', sa.Date(), nullable=True),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('parent_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('personal_number', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('birth_country_id', sa.UUID(), nullable=True),
    sa.Column('birth_municipality_id', sa.UUID(), nullable=True),
    sa.Column('birth_place_id', sa.UUID(), nullable=True),
    sa.Column('birth_municipality_foreign', sa.String(length=200), nullable=True),
    sa.Column('birth_place_foreign', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('residence_municipality_id', sa.UUID(), nullable=True),
    sa.Column('residence_place_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('is_automatic', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('practical_hours', sa.Integer(), nullable=True),
    sa.Column('theory_hours', sa.Integer(), nullable=True),
    sa.Column('practical_hours_realized', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('protocol_number', sa.String(length=50), nullable=True),
    sa.Column('medical_certificate', sa.Boolean(), nullable=True),
    sa.Column('medical_certificate_number', sa.String(length=50), nullable=True),
    sa.Column('medical_certificate_date', sa.Date(), nullable=True),
    sa.Column('verification_flag', sa.Boolean(), nullable=True),
    sa.Column('red_cross_certificate', sa.Boolean(), nullable=True),
    sa.Column('id_card_copy', sa.Boolean(), nullable=True),
    sa.Column('lecturer_id', sa.UUID(), nullable=True),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('has_extra_hours', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['birth_country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['birth_municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['birth_place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['residence_municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['residence_place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_candidates_tenant_code')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index('idx_candidates_archived', ['tenant_id', 'is_archived'], unique=False)
        batch_op.create_index('idx_candidates_category', ['tenant_id', 'category_id'], unique=False)
        batch_op.create_index('idx_candidates_instructor', ['tenant_id', 'instructor_id'], unique=False)
        batch_op.create_index('idx_candidates_personal_number', ['tenant_id', 'personal_number'], unique=False)
        batch_op.create_index('idx_candidates_registration_date', ['tenant_id', 'registration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('expense_type_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expense_type_id'], ['expense_types.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('idx_expenses_date', ['tenant_id', 'date'], unique=False)
        batch_op.create_index('idx_expenses_vehicle', ['tenant_id', 'vehicle_id'], unique=False)

    op.create_table('candidate_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('test_number', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('passing_score', sa.Integer(), nullable=True),
    sa.Column('date_taken', sa.Date(), nullable=True),
    sa.Column('is_passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_tests', schema=None) as batch_op:
        batch_op.create_index('idx_candidate_tests_candidate', ['tenant_id', 'candidate_id'], unique=False)
        batch_op.create_index('idx_candidate_tests_date', ['tenant_id', 'date_taken'], unique=False)

    op.create_table('instructor_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'instructor_id', 'candidate_id', name='uq_instructor_payment_candidate')
    )
    with op.batch_alter_table('instructor_payments', schema=None) as batch_op:
        batch_op.create_index('idx_instructor_payments_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index('idx_instructor_payments_tenant', ['tenant_id', 'instructor_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('received_by_user_id', sa.UUID(), nullable=True),
    sa.Column('is_supplementary', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('idx_payments_candidate', ['tenant_id', 'candidate_id'], unique=False)
        batch_op.create_index('idx_payments_date', ['tenant_id', 'payment_date'], unique=False)

    op.create_table('practical_hour_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('date_realized', sa.Date(), nullable=False),
    sa.Column('time_realized', sa.Time(), nullable=False),
    sa.Column('hours_count', sa.Integer(), nullable=True),
    sa.Column('price_per_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practical_hour_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_practical_sessions_candidate', ['tenant_id', 'candidate_id'], unique=False)
        batch_op.create_index('idx_practical_sessions_date', ['tenant_id', 'date_realized'], unique=False)
        batch_op.create_index('idx_practical_sessions_instructor', ['tenant_id', 'instructor_id'], unique=False)

    op.create_table('scheduled_lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('practical_session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['practical_session_id'], ['practical_hour_sessions.id'], use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_lessons', schema=None) as batch_op:
        batch_op.create_index('idx_scheduled_lessons_candidate_date', ['tenant_id', 'candidate_id', 'scheduled_date'], unique=False)
        batch_op.create_index('idx_scheduled_lessons_date', ['tenant_id', 'scheduled_date', 'start_time'], unique=False)
        batch_op.create_index('idx_scheduled_lessons_instructor_date', ['tenant_id', 'instructor_id', 'scheduled_date'], unique=False)

    op.create_table('supplementary_registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('is_automatic', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('practical_hours', sa.Integer(), nullable=True),
    sa.Column('theory_hours', sa.Integer(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplementary_registrations', schema=None) as batch_op:
        batch_op.create_index('idx_supplementary_registrations_candidate', ['tenant_id', 'candidate_id'], unique=False)
        batch_op.create_index('idx_supplementary_registrations_date', ['tenant_id', 'registration_date'], unique=False)

    op.create_table('theory_hour_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('chapter_topics', sa.String(length=100), nullable=False),
    sa.Column('date_realized', sa.Date(), nullable=True),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.Column('hours_count', sa.Integer(), nullable=True),
    sa.Column('is_realized', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'session_number', name='uq_theory_session_candidate_number')
    )
    with op.batch_alter_table('theory_hour_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_theory_sessions_candidate', ['tenant_id', 'candidate_id'], unique=False)
        batch_op.create_index('idx_theory_sessions_date', ['tenant_id', 'date_realized'], unique=False)

    op.create_table('verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('verification_date', sa.Date(), nullable=True),
    sa.Column('theory_hours_start', sa.Date(), nullable=True),
    sa.Column('theory_hours_end', sa.Date(), nullable=True),
    sa.Column('practical_hours_start', sa.Date(), nullable=True),
    sa.Column('practical_hours_end', sa.Date(), nullable=True),
    sa.Column('sequence_number', sa.String(length=50), nullable=True),
    sa.Column('lecturer_id', sa.UUID(), nullable=True),
    sa.Column('instructor_id', sa.UUID(), nullable=True),
    sa.Column('red_cross_cert', sa.Boolean(), nullable=True),
    sa.Column('id_card_copy', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['lecturer_id'], ['instructors.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.create_index('idx_verifications_candidate', ['tenant_id', 'candidate_id'], unique=False)
        batch_op.create_index('idx_verifications_category', ['tenant_id', 'category_id'], unique=False)
        batch_op.create_index('idx_verifications_date', ['tenant_id', 'verification_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.drop_index('idx_verifications_date')
        batch_op.drop_index('idx_verifications_category')
        batch_op.drop_index('idx_verifications_candidate')

    op.drop_table('verifications')
    with op.batch_alter_table('theory_hour_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_theory_sessions_date')
        batch_op.drop_index('idx_theory_sessions_candidate')

    op.drop_table('theory_hour_sessions')
    with op.batch_alter_table('supplementary_registrations', schema=None) as batch_op:
        batch_op.drop_index('idx_supplementary_registrations_date')
        batch_op.drop_index('idx_supplementary_registrations_candidate')

    op.drop_table('supplementary_registrations')
    with op.batch_alter_table('scheduled_lessons', schema=None) as batch_op:
        batch_op.drop_index('idx_scheduled_lessons_instructor_date')
        batch_op.drop_index('idx_scheduled_lessons_date')
        batch_op.drop_index('idx_scheduled_lessons_candidate_date')

    op.drop_table('scheduled_lessons')
    with op.batch_alter_table('practical_hour_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_practical_sessions_instructor')
        batch_op.drop_index('idx_practical_sessions_date')
        batch_op.drop_index('idx_practical_sessions_candidate')

    op.drop_table('practical_hour_sessions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('idx_payments_date')
        batch_op.drop_index('idx_payments_candidate')

    op.drop_table('payments')
    with op.batch_alter_table('instructor_payments', schema=None) as batch_op:
        batch_op.drop_index('idx_instructor_payments_tenant')
        batch_op.drop_index('idx_instructor_payments_status')

    op.drop_table('instructor_payments')
    with op.batch_alter_table('candidate_tests', schema=None) as batch_op:
        batch_op.drop_index('idx_candidate_tests_date')
        batch_op.drop_index('idx_candidate_tests_candidate')

    op.drop_table('candidate_tests')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('idx_expenses_vehicle')
        batch_op.drop_index('idx_expenses_date')

    op.drop_table('expenses')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_tenant_id'))
        batch_op.drop_index('idx_candidates_registration_date')
        batch_op.drop_index('idx_candidates_personal_number')
        batch_op.drop_index('idx_candidates_instructor')
        batch_op.drop_index('idx_candidates_category')
        batch_op.drop_index('idx_candidates_archived')

    op.drop_table('candidates')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_tenant_id'))

    op.drop_table('vehicles')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_recipient')
        batch_op.drop_index('idx_messages_conversation')

    op.drop_table('messages')
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_places_municipality_id'))

    op.drop_table('places')
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instructors_user_id'))
        batch_op.drop_index(batch_op.f('ix_instructors_tenant_id'))

    op.drop_table('instructors')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('idx_conversations_tenant')

    op.drop_table('conversations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_logs_user')
        batch_op.drop_index('idx_audit_logs_tenant_date')
        batch_op.drop_index('idx_audit_logs_entity')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))

    op.drop_table('users')
    with op.batch_alter_table('municipalities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_municipalities_country_id'))

    op.drop_table('municipalities')
    with op.batch_alter_table('expense_types', schema=None) as batch_op:
        batch_op.drop_index('idx_expense_types_tenant')

    op.drop_table('expense_types')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_tenant_id'))

    op.drop_table('categories')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))
        batch_op.drop_index(batch_op.f('ix_tenants_is_active'))

    op.drop_table('tenants')
    op.drop_table('countries')
    # ### end Alembic commands ###
