"""add insurance_expiry and license_expiry columns

Revision ID: 5c1aac1d237c
Revises: 718e73e774fc
Create Date: 2026-03-14 16:31:27.195341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1aac1d237c'
down_revision = '718e73e774fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_expiry', sa.Date(), nullable=True))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_expiry', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('insurance_expiry')

    with op.batch_alter_table('instructors', schema=None) as batch_op:
        batch_op.drop_column('license_expiry')

    # ### end Alembic commands ###
