"""add_exams_table

Revision ID: 718e73e774fc
Revises: ec8d8d0b300e
Create Date: 2026-03-14 16:20:44.759738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718e73e774fc'
down_revision = 'ec8d8d0b300e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('exam_type', sa.String(length=20), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('examiner_name', sa.String(length=200), nullable=True),
    sa.Column('exam_location', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index('idx_exams_tenant_candidate', ['tenant_id', 'candidate_id'], unique=False)
        batch_op.create_index('idx_exams_tenant_date', ['tenant_id', 'exam_date'], unique=False)
        batch_op.create_index('idx_exams_tenant_type_result', ['tenant_id', 'exam_type', 'result'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index('idx_exams_tenant_type_result')
        batch_op.drop_index('idx_exams_tenant_date')
        batch_op.drop_index('idx_exams_tenant_candidate')

    op.drop_table('exams')
    # ### end Alembic commands ###
