"""add lesson_chapters table and chapter_topics to practical_hours

Revision ID: ec8d8d0b300e
Revises: 3559cc0f8f90
Create Date: 2026-03-11 01:22:14.368364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8d8d0b300e'
down_revision = '3559cc0f8f90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_chapters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('chapter_type', sa.String(length=10), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('chapter_topics', sa.String(length=200), nullable=False),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.Column('hours_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("chapter_type IN ('theory', 'practical')", name='ck_lesson_chapter_type'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'category_id', 'chapter_type', 'session_number', name='uq_lesson_chapter_tenant_cat_type_num')
    )
    with op.batch_alter_table('lesson_chapters', schema=None) as batch_op:
        batch_op.create_index('idx_lesson_chapters_tenant_cat_type', ['tenant_id', 'category_id', 'chapter_type'], unique=False)

    with op.batch_alter_table('practical_hour_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_topics', sa.String(length=200), nullable=True))

    with op.batch_alter_table('scheduled_lessons', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'practical_hour_sessions', ['practical_session_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_lessons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('practical_hour_sessions', schema=None) as batch_op:
        batch_op.drop_column('chapter_topics')

    with op.batch_alter_table('lesson_chapters', schema=None) as batch_op:
        batch_op.drop_index('idx_lesson_chapters_tenant_cat_type')

    op.drop_table('lesson_chapters')
    # ### end Alembic commands ###
