from app.models.tenant_model import Tenant  # noqa: F401
from app.models.user_model import User  # noqa: F401
from app.models.country_model import Country  # noqa: F401
from app.models.municipality_model import Municipality  # noqa: F401
from app.models.place_model import Place  # noqa: F401
from app.models.category_model import Category  # noqa: F401
from app.models.instructor_model import Instructor  # noqa: F401
from app.models.vehicle_model import Vehicle  # noqa: F401
from app.models.candidate_model import Candidate  # noqa: F401
from app.models.instructor_payment_model import InstructorPayment  # noqa: F401
from app.models.scheduled_lesson_model import ScheduledLesson  # noqa: F401
from app.models.conversation_model import Conversation  # noqa: F401
from app.models.message_model import Message  # noqa: F401
from app.models.theory_hour_session_model import TheoryHourSession  # noqa: F401
from app.models.practical_hour_session_model import PracticalHourSession  # noqa: F401
from app.models.supplementary_registration_model import SupplementaryRegistration  # noqa: F401
from app.models.verification_model import Verification  # noqa: F401
from app.models.payment_model import Payment  # noqa: F401
from app.models.expense_type_model import ExpenseType  # noqa: F401
from app.models.expense_model import Expense  # noqa: F401
from app.models.candidate_test_model import CandidateTest  # noqa: F401
from app.models.audit_log_model import AuditLog  # noqa: F401
from app.models.lesson_chapter_model import LessonChapter  # noqa: F401
from app.models.exam_model import Exam  # noqa: F401
